### ISSUE TITLE
2022 ToDo list

### ISSUE THREAD

**Issue by Zhenglei-BCS** [Zhenglei-BCS/beemixtox_public#2]
- [x] Guidance on supp ==> Ismael should give a skeleton. 
- [x] Finalize the supplemental material
     - [x] Expand the filtering and curation of data.
     - [x] Confusion matrix. 
- [x] New data and redo the analysis.  ==> Ismael should send the new code (pre-processing and figures). 
- [x] Check OPP DB bee study variances, and CV

**Comment by Zhenglei-BCS** [comment]
- [x] US EPA Ecotox db (not necessary with regulatory design) comparison OPP pesticide Ecotoxicity (regulatory endpoints) ==> check the CV.
